"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Check, LayoutDashboard, RotateCcw, Sparkles, Wand2 } from "lucide-react";
import { toast } from "sonner";
import ConnectedWallets from "./ConnectedWallets";
import PortfolioDashboard from "./PortfolioDashboard";
import SecurityCenter from "./SecurityCenter";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { applyDashboardPlan, createDashboard, loadWorkspace, planDashboard, undoDashboard, updateDashboard, type Dashboard, type DashboardPlan, type DashboardWidget } from "@/lib/dashboardApi";

const fallbackDashboard: Dashboard = { _id: "local-preview", userId: "browser-preview", name: "My AvhiSafe dashboard", slug: "main", theme: "system", currency: "USD", density: "comfortable", isDefault: true, filters: {}, widgets: [
  { id: "connected-wallets-default", type: "connected-wallets", title: "Connected wallets", enabled: true, position: 0, width: "full", config: {} },
  { id: "portfolio-value-default", type: "portfolio-value", title: "Portfolio overview", enabled: true, position: 1, width: "full", config: {} },
  { id: "security-score-default", type: "security-score", title: "Security center", enabled: true, position: 2, width: "full", config: {} },
] };

function widgetLabel(widget: DashboardWidget) { return widget.title || widget.type.replaceAll("-", " "); }
function isLocal(id: string) { return id === "local-preview"; }

export default function DynamicDashboard() {
  const [dashboard, setDashboard] = useState<Dashboard>(fallbackDashboard);
  const [prompt, setPrompt] = useState("Make this dashboard dark and compact");
  const [plan, setPlan] = useState<DashboardPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [planning, setPlanning] = useState(false);
  const [applying, setApplying] = useState(false);
  const [backendConnected, setBackendConnected] = useState(false);

  useEffect(() => { loadWorkspace().then((data) => { setDashboard(data.dashboard); setBackendConnected(true); }).catch(() => setBackendConnected(false)).finally(() => setLoading(false)); }, []);
  const widgets = useMemo(() => [...dashboard.widgets].filter((widget) => widget.enabled).sort((a, b) => a.position - b.position), [dashboard.widgets]);

  const persist = async (next: Dashboard, summary: string) => {
    setDashboard(next);
    if (!isLocal(next._id)) { try { const result = await updateDashboard(next._id, { theme: next.theme, currency: next.currency, density: next.density, widgets: next.widgets, filters: next.filters, revisionSummary: summary }); setDashboard(result.dashboard); } catch { toast.error("Saved locally, but the backend is unavailable."); } }
  };
  const toggleWidget = async (id: string) => { const widgets = dashboard.widgets.map((widget) => widget.id === id ? { ...widget, enabled: !widget.enabled } : widget); await persist({ ...dashboard, widgets }, "Changed widget visibility"); };
  const moveWidget = async (id: string, delta: number) => { const widgets = [...dashboard.widgets].sort((a, b) => a.position - b.position); const index = widgets.findIndex((widget) => widget.id === id); const nextIndex = index + delta; if (index < 0 || nextIndex < 0 || nextIndex >= widgets.length) return; [widgets[index], widgets[nextIndex]] = [widgets[nextIndex], widgets[index]]; await persist({ ...dashboard, widgets: widgets.map((widget, position) => ({ ...widget, position })) }, "Reordered widgets"); };
  const runPlan = async () => { const requestedPrompt = prompt.trim() || "Make this dashboard dark and compact"; setPrompt(requestedPrompt); setPlanning(true); try { const result = isLocal(dashboard._id) ? { plan: localPlan(requestedPrompt) } : await planDashboard(dashboard._id, requestedPrompt); setPlan(result.plan); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to create AI plan."); } finally { setPlanning(false); } };
  const applyPlan = async () => { if (!plan || !prompt.trim()) return; setApplying(true); try { if (isLocal(dashboard._id)) { setDashboard(localApply(dashboard, plan)); } else { const result = await applyDashboardPlan(dashboard._id, prompt, plan); setDashboard(result.dashboard); } setPlan(null); toast.success("Your dashboard was updated. Other users were not affected."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to apply dashboard plan."); } finally { setApplying(false); } };
  const undo = async () => { try { if (isLocal(dashboard._id)) { toast.info("Undo becomes available after the backend workspace is connected."); return; } const result = await undoDashboard(dashboard._id); setDashboard(result.dashboard); toast.success("Previous dashboard revision restored."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to undo dashboard change."); } };
  const newDashboard = async () => { try { const { _id: _ignoredId, userId: _ignoredUserId, ...dashboardFields } = dashboard; const result = await createDashboard({ ...dashboardFields, slug: `dashboard-${Date.now()}`, name: "New personal dashboard", isDefault: false }); setDashboard(result.dashboard); toast.success("New personal dashboard created."); } catch { toast.info("Connect MongoDB and authentication to create synced dashboards."); } };

  return <section className="mt-12 flex flex-col gap-6 border-t border-primary/10 pt-12"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-primary/50">Universal workspace</p><h2 className="mt-2 flex items-center gap-3 text-4xl font-black tracking-tight"><LayoutDashboard className="size-8" />{dashboard.name}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-primary/60">Every account gets its own widgets, layout, AI changes, and revision history. Changes here affect only this user dashboard.</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-2 text-xs font-bold ${backendConnected ? "bg-emerald-500/10 text-emerald-700" : "bg-amber-500/10 text-amber-700"}`}>{backendConnected ? "Synced to MongoDB" : "Local preview mode"}</span><Button variant="outline" className="gap-2" onClick={newDashboard}><LayoutDashboard className="size-4" />New dashboard</Button><Button variant="ghost" className="gap-2" onClick={undo}><RotateCcw className="size-4" />Undo</Button></div></div>
    <div className="rounded-2xl border border-primary/10 bg-primary/[0.03] p-5"><div className="flex items-center gap-2 text-sm font-bold"><Sparkles className="size-4 text-primary/60" />Ask AI to customize this dashboard</div><div className="mt-3 flex flex-col gap-3 md:flex-row"><Input value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void runPlan(); }} placeholder="Make it compact, add security and NFT widgets, and use dark mode" /><Button className="gap-2 md:min-w-32" disabled={planning} onClick={runPlan}><Wand2 className="size-4" />{planning ? "Planning…" : "Plan changes"}</Button></div>{plan && <div className="mt-4 rounded-xl bg-background p-4"><p className="font-semibold">{plan.explanation}</p>{plan.warnings.map((warning) => <p key={warning} className="mt-2 text-sm text-amber-700">{warning}</p>)}<div className="mt-3 flex flex-wrap gap-2">{plan.operations.map((operation, index) => <span key={`${operation.type}-${index}`} className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold">{String(operation.type).replaceAll("_", " ")} {String(operation.widgetType || operation.value || "")}</span>)}</div><div className="mt-4 flex gap-2"><Button disabled={applying || plan.operations.length === 0} onClick={applyPlan} className="gap-2"><Check className="size-4" />{applying ? "Applying…" : "Apply to my dashboard"}</Button><Button variant="ghost" onClick={() => setPlan(null)}>Cancel</Button></div></div>}</div>
    <div className="grid gap-3 rounded-2xl border border-primary/10 bg-background p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-primary/50">Personal widget layout</p><p className="mt-1 text-sm text-primary/60">Enable, hide, reorder, and customize widgets independently.</p></div><div className="flex gap-2"><select value={dashboard.theme} onChange={(event) => void persist({ ...dashboard, theme: event.target.value as Dashboard["theme"] }, "Changed theme")} className="rounded-lg border border-primary/10 bg-background px-3 py-2 text-sm"><option value="system">System theme</option><option value="light">Light theme</option><option value="dark">Dark theme</option></select><select value={dashboard.density} onChange={(event) => void persist({ ...dashboard, density: event.target.value as Dashboard["density"] }, "Changed dashboard density")} className="rounded-lg border border-primary/10 bg-background px-3 py-2 text-sm"><option value="comfortable">Comfortable</option><option value="compact">Compact</option><option value="analytics">Analytics</option></select></div></div><div className="flex flex-wrap gap-2">{dashboard.widgets.sort((a, b) => a.position - b.position).map((widget) => <div key={widget.id} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-xs ${widget.enabled ? "border-primary/20" : "border-primary/5 opacity-50"}`}><button onClick={() => void toggleWidget(widget.id)} className="font-semibold">{widget.enabled ? "Hide" : "Show"} {widgetLabel(widget)}</button><button aria-label="Move widget up" onClick={() => void moveWidget(widget.id, -1)}><ArrowUp className="size-3" /></button><button aria-label="Move widget down" onClick={() => void moveWidget(widget.id, 1)}><ArrowDown className="size-3" /></button></div>)}</div></div>
    {loading ? <div className="rounded-2xl border border-primary/10 p-8 text-center text-sm text-primary/60">Loading your personal dashboard…</div> : <div className="flex flex-col gap-6">{widgets.map((widget) => <div key={widget.id} className="rounded-2xl border border-primary/10 bg-background/30 p-3"><div className="mb-3 flex items-center justify-between px-2"><p className="text-xs font-bold uppercase tracking-wider text-primary/45">{widgetLabel(widget)}</p><span className="text-xs text-primary/40">{widget.width}</span></div>{widget.type === "connected-wallets" && <ConnectedWallets />}{widget.type === "portfolio-value" && <PortfolioDashboard />}{widget.type === "security-score" && <SecurityCenter />}{!["connected-wallets", "portfolio-value", "security-score"].includes(widget.type) && <div className="rounded-xl bg-primary/[0.03] p-8 text-center"><p className="font-semibold">{widgetLabel(widget)} widget enabled</p><p className="mt-2 text-sm text-primary/55">This dynamic widget slot is ready for the next blockchain data adapter.</p></div>}</div>)}</div>}
  </section>;
}

function localPlan(prompt: string): DashboardPlan { const text = prompt.toLowerCase(); const operations: Array<Record<string, unknown>> = []; if (text.includes("dark")) operations.push({ type: "set_theme", value: "dark" }); if (text.includes("light")) operations.push({ type: "set_theme", value: "light" }); if (text.includes("compact")) operations.push({ type: "set_density", value: "compact" }); if (text.includes("nft")) operations.push({ type: "enable_widget", widgetType: "nft-gallery" }); if (text.includes("defi")) operations.push({ type: "enable_widget", widgetType: "defi-positions" }); if (text.includes("security") || text.includes("risk")) operations.push({ type: "enable_widget", widgetType: "security-score" }, { type: "enable_widget", widgetType: "risk-summary" }); return { intent: operations.length ? "customize_dashboard" : "unsupported", explanation: operations.length ? `Prepared ${operations.length} local dashboard operation${operations.length === 1 ? "" : "s"}.` : "Try asking for theme, density, or supported widgets.", operations, warnings: [], requiresApproval: operations.length > 0 }; }
function localApply(dashboard: Dashboard, plan: DashboardPlan): Dashboard { const next = structuredClone(dashboard); for (const operation of plan.operations) { const type = String(operation.type); if (type === "set_theme") next.theme = String(operation.value) as Dashboard["theme"]; if (type === "set_density") next.density = String(operation.value) as Dashboard["density"]; if (type === "enable_widget") { const widgetType = String(operation.widgetType); const existing = next.widgets.find((widget) => widget.type === widgetType); if (existing) existing.enabled = true; else next.widgets.push({ id: `${widgetType}-local`, type: widgetType, title: widgetType.replaceAll("-", " "), enabled: true, position: next.widgets.length, width: "medium", config: {} }); } } return next; }
